### Боб основал собственную компанию мобильной связи. Он хочет дать жесткий бой таким крупным компаниям, как Apple, Samsung и т.д. Он не знает, как оценить цену мобильных телефонов, которые создает его компания. На этом конкурентном рынке мобильных телефонов вы не можете просто предполагать что-то. Чтобы решить эту проблему, он собирает данные о продажах мобильных телефонов различных компаний.

### Цель: выяснить связь между функциями мобильного телефона и его продажной ценой. 

In [1]:
import numpy as np
import pandas as pd

In [2]:
testdf = pd.read_csv('test.csv')
traindf = pd.read_csv('train.csv')
traindf.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
print(traindf['px_height'].all())

False


In [4]:
traindf['px_height'].replace(0, traindf['px_height'].mean(), inplace=True)

In [5]:
print(traindf['px_height'].all())

True


In [6]:
traindf['px_size'] = np.round((traindf['px_height'] * traindf['px_width']), 2)
traindf.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  three_g  \
0        188        2  ...       756  2549     9     7         19        0   
1        136        3  ...      1988  2631    17     3          7        1   
2        145        5  ...      1716  2603    11     2          9        1   
3        131        6  ...      1786  2769    16     8         11        1   
4        141        2  ...      1212  1411     8     2         15        1   

   touch_screen  wifi  price_range    px_size  
0             0     1            1    15120.0  
1             1     0            2  1799140.0  
2             1     0            2  2167308.0  
3             0     0            2  2171776.0  
4             1     0            1  1464096.0  

[5 rows x 22 columns]

In [7]:
traindf['px_size'] = traindf['px_size'] / 926

In [8]:
traindf.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  three_g  \
0        188        2  ...       756  2549     9     7         19        0   
1        136        3  ...      1988  2631    17     3          7        1   
2        145        5  ...      1716  2603    11     2          9        1   
3        131        6  ...      1786  2769    16     8         11        1   
4        141        2  ...      1212  1411     8     2         15        1   

   touch_screen  wifi  price_range      px_size  
0             0     1            1    16.328294  
1             1     0            2  1942.915767  
2             1     0            2  2340.505400  
3             0     0            2  2345.330454  
4             1     0            1  1581.097192  

[5 rows x 22 columns]

## Feature Selection

In [9]:
traindf.drop(labels=['blue', 'dual_sim', 'm_dep', 'mobile_wt', 'talk_time', 'px_height', 'px_width'], inplace=True, axis=1)
testdf.drop(labels=['blue', 'dual_sim', 'm_dep', 'mobile_wt', 'talk_time', 'px_height', 'px_width'], inplace=True, axis=1)

In [10]:
print(traindf['sc_h'].all())
print(traindf['sc_w'].all())

True
False


In [11]:
traindf['sc_w'].replace(0, int(traindf['sc_w'].mean()), inplace=True)

In [12]:
print(traindf['sc_w'].all())

True


In [13]:
traindf['sc_size'] = np.round((traindf['sc_h'] * traindf['sc_w']), 2)
traindf.drop(['sc_h', 'sc_w'], axis=1, inplace=True)

In [14]:
traindf.head()

battery_power  clock_speed  fc  four_g  int_memory  n_cores  pc   ram  \
0            842          2.2   1       0           7        2   2  2549   
1           1021          0.5   0       1          53        3   6  2631   
2            563          0.5   2       1          41        5   6  2603   
3            615          2.5   0       0          10        6   9  2769   
4           1821          1.2  13       1          44        2  14  1411   

   three_g  touch_screen  wifi  price_range      px_size  sc_size  
0        0             0     1            1    16.328294       63  
1        1             1     0            2  1942.915767       51  
2        1             1     0            2  2340.505400       22  
3        1             0     0            2  2345.330454      128  
4        1             1     0            1  1581.097192       16

In [15]:
traindf.shape

(2000, 14)

In [16]:
traindf.all()

battery_power     True
clock_speed       True
fc               False
four_g           False
int_memory        True
n_cores           True
pc               False
ram               True
three_g          False
touch_screen     False
wifi             False
price_range      False
px_size           True
sc_size           True
dtype: bool

In [17]:
traindf['pc'].replace(0, np.round(traindf['pc'].mean(), 0), inplace=True)

In [18]:
traindf.head()

battery_power  clock_speed  fc  four_g  int_memory  n_cores    pc   ram  \
0            842          2.2   1       0           7        2   2.0  2549   
1           1021          0.5   0       1          53        3   6.0  2631   
2            563          0.5   2       1          41        5   6.0  2603   
3            615          2.5   0       0          10        6   9.0  2769   
4           1821          1.2  13       1          44        2  14.0  1411   

   three_g  touch_screen  wifi  price_range      px_size  sc_size  
0        0             0     1            1    16.328294       63  
1        1             1     0            2  1942.915767       51  
2        1             1     0            2  2340.505400       22  
3        1             0     0            2  2345.330454      128  
4        1             1     0            1  1581.097192       16

In [19]:
traindf['pc'].head()

0     2.0
1     6.0
2     6.0
3     9.0
4    14.0
Name: pc, dtype: float64

In [20]:
traindf.all()

battery_power     True
clock_speed       True
fc               False
four_g           False
int_memory        True
n_cores           True
pc                True
ram               True
three_g          False
touch_screen     False
wifi             False
price_range      False
px_size           True
sc_size           True
dtype: bool

In [21]:
testdf['sc_w'].replace(0, int(testdf['sc_w'].mean()), inplace=True)

In [22]:
print(testdf['sc_w'].all())

True


In [23]:
print(testdf['sc_h'].all())

True


In [24]:
testdf['sc_size'] = np.round((testdf['sc_h'] * testdf['sc_w']), 0)
testdf.drop(['sc_h', 'sc_w'], axis=1, inplace=True)

In [25]:
testdf.head()

id  battery_power  clock_speed  fc  four_g  int_memory  n_cores  pc   ram  \
0   1           1043          1.8  14       0           5        3  16  3476   
1   2            841          0.5   4       1          61        5  12  3895   
2   3           1807          2.8   1       0          27        3   4  2396   
3   4           1546          0.5  18       1          25        8  20  3893   
4   5           1434          1.4  11       1          49        6  18  1773   

   three_g  touch_screen  wifi  sc_size  
0        0             1     0       84  
1        1             0     0       30  
2        0             1     1      170  
3        1             1     0       50  
4        1             0     1      120

In [26]:
traindf.head()

battery_power  clock_speed  fc  four_g  int_memory  n_cores    pc   ram  \
0            842          2.2   1       0           7        2   2.0  2549   
1           1021          0.5   0       1          53        3   6.0  2631   
2            563          0.5   2       1          41        5   6.0  2603   
3            615          2.5   0       0          10        6   9.0  2769   
4           1821          1.2  13       1          44        2  14.0  1411   

   three_g  touch_screen  wifi  price_range      px_size  sc_size  
0        0             0     1            1    16.328294       63  
1        1             1     0            2  1942.915767       51  
2        1             1     0            2  2340.505400       22  
3        1             0     0            2  2345.330454      128  
4        1             1     0            1  1581.097192       16

In [27]:
traindf.drop(['px_size'], axis=1, inplace=True)

In [28]:
y_train = traindf['price_range']
traindf.drop(['price_range'], inplace=True, axis=1)

In [29]:
y_train = pd.DataFrame(y_train)

In [30]:
X_train = traindf

In [31]:
X_test = testdf

In [32]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [33]:
accuracyDetails = {}

In [34]:
cv = KFold(n_splits=10, random_state=1, shuffle=True)

## Random Forest Cross validation

In [35]:
model = RandomForestClassifier(n_estimators = 90)
scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)

In [36]:
model.fit(X_train, y_train['price_range'])
feature_importances=pd.DataFrame({'features':X_train.columns,'feature_importance':model.feature_importances_})

with pd.option_context("display.max_rows", 100):
        print(feature_importances.sort_values('feature_importance',ascending=False))

         features  feature_importance
7             ram            0.544497
0   battery_power            0.105440
11        sc_size            0.066244
4      int_memory            0.063291
6              pc            0.049625
1     clock_speed            0.048568
2              fc            0.042641
5         n_cores            0.036513
10           wifi            0.011958
3          four_g            0.011340
9    touch_screen            0.010831
8         three_g            0.009054


In [37]:
print(scores*100)

[77.  78.  82.  82.5 79.5 79.5 85.  82.  80.5 79.5]


In [38]:
print("Mean Accuracy for the Model using Random Forest = {}".format(np.round(scores.mean()*100, 2)))

Mean Accuracy for the Model using Random Forest = 80.55


## SVC Cross validation

In [39]:
model = SVC()
scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)

In [40]:
print(scores*100)

[78.  79.  84.  86.5 78.5 81.  86.  83.5 81.5 82.5]


In [41]:
print("Mean Accuracy for the Model using SVM = {}".format(np.round(scores.mean()*100, 2)))

Mean Accuracy for the Model using SVM = 82.05


## KNeighborsClassifier Cross validation

In [42]:
model = KNeighborsClassifier(n_neighbors=7)
scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)

In [43]:
print(scores*100)

[77.5 77.  81.5 83.5 78.5 83.  82.  78.  83.5 79.5]


In [44]:
print("Mean Accuracy for the Model using KNN = {}".format(np.round(scores.mean()*100, 2)))

Mean Accuracy for the Model using KNN = 80.4


In [45]:
accuracyDetails['KNN'] = np.round(scores.mean()*100, 2)

## Logistic Regression Cross validation

In [46]:
model = LogisticRegression(solver='liblinear')
scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)

In [47]:
print(scores*100)

[70.5 73.5 68.5 78.5 75.5 67.5 72.  79.  72.5 70.5]


In [48]:
print("Mean Accuracy for the Model using Logistic Regression = {}".format(np.round(scores.mean()*100, 2)))

Mean Accuracy for the Model using Logistic Regression = 72.8


## Using Support Vector Machine for Predictions

In [49]:
SVM = SVC()
SVM.fit(X_train, y_train['price_range'])

SVC()

In [50]:
df_y_pred = pd.DataFrame(y_pred)

NameError: name 'y_pred' is not defined

In [51]:
df_y_pred.head(30)

NameError: name 'df_y_pred' is not defined

In [ ]:
feature_importances=pd.DataFrame({'features':X_train.columns,'feature_importance':SVM.featureimportances})

with pd.option_context("display.max_rows", 100):
        print(feature_importances.sort_values('feature_importance',ascending=False))